FROM ros:humble-ros-base

SHELL ["/bin/bash", "-c"]

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    git \
    python3-colcon-common-extensions \
    ros-humble-rclcpp-components \
    ros-humble-geometry-msgs \
    clang-format \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspaces/code

CMD ["/bin/bash"]
