services:
  publisher:
    image: basic:deploy
    build:
      context: ..
      dockerfile: docker/Dockerfile.deploy
    container_name: basic-publisher
    # TODO: 启动发布节点
    command: /bin/bash -c "source /opt/ros/humble/setup.bash && source /workspaces/code/install/setup.bash && exec ./install/basic_topic/lib/basic_topic/publisher_node"
    networks:
      - ros-net
    tty: true

  subscriber:
    image: basic:deploy
    build:
      context: ..
      dockerfile: docker/Dockerfile.deploy
    container_name: basic-subscriber
    # TODO: 启动订阅节点
    command: /bin/bash -c "source /opt/ros/humble/setup.bash && source /workspaces/code/install/setup.bash && exec ./install/basic_topic/lib/basic_topic/subscriber_node"
    networks:
      - ros-net
    tty: true

networks:
  ros-net:
    driver: bridge
